-- 양계장 관리 시스템 데이터베이스 구조
-- 외래키 제약조건 먼저 삭제 (테이블 드롭)
DROP TABLE IF EXISTS `CHICKEN_INOCULATION_HISTORY`;
DROP TABLE IF EXISTS `chicken_weight_history`;
DROP TABLE IF EXISTS `CHICKEN`;
DROP TABLE IF EXISTS `DANGER_NOTICE`;
DROP TABLE IF EXISTS `CHICKEN_BATCH`;
DROP TABLE IF EXISTS `FARM_MANAGEMENT`;
DROP TABLE IF EXISTS `FARM_STATUS`;
DROP TABLE IF EXISTS `NOTE`;
DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `CHICKEN_FARM`;

-- 기본 테이블 생성
CREATE TABLE `CHICKEN_FARM` (
	`FARM_NUM` INT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '축사 아이디',
	`FARM_NAME` VARCHAR(20) NOT NULL COMMENT '축사 이름'
);

CREATE TABLE `FARM_STATUS` (
	`FARM_STATUS_NUM` INT AUTO_INCREMENT NOT NULL COMMENT '축사 상태 아이디',
	`NO2_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '이산화질소',
	`TEMP_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '온도',
	`HUM_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '습도',
	`LUX_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '조명',
	`CO_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '일산화탄소',
	`CO2_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '이산화탄소',
	`NH3_DATA` FLOAT NOT NULL DEFAULT 0 COMMENT '암모니아',
	`REC_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '기록시간',
	`FARM_ID` INT NOT NULL COMMENT '축사 아이디',
	PRIMARY KEY (`FARM_STATUS_NUM`),
	FOREIGN KEY (`FARM_ID`) REFERENCES `CHICKEN_FARM`(`FARM_NUM`)
);

CREATE TABLE `FARM_MANAGEMENT` (
	`MANAGEMENT_NUM` INT AUTO_INCREMENT NOT NULL COMMENT '관리 번호',
	`FEED_CONSUMPTION_G` FLOAT NOT NULL DEFAULT 0 COMMENT '전체 모이 소비량',
	`WATER_CONSUMPTION_ML` FLOAT NOT NULL DEFAULT 0 COMMENT '전체 물 소비량',
	`REC_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '기록 시간',
	`FARM_NUM` INT NOT NULL COMMENT '축사 아이디',
	PRIMARY KEY (`MANAGEMENT_NUM`),
	FOREIGN KEY (`FARM_NUM`) REFERENCES `CHICKEN_FARM`(`FARM_NUM`)
);

SELECT * FROM farm_management;

CREATE TABLE `CHICKEN_BATCH` (
	`BATCH_ID` VARCHAR(20) NOT NULL COMMENT '배치 번호(EX>2025-001)',
	`ENTRY_DATE` DATETIME NOT NULL COMMENT '입식일(부화일)',
	`INITIAL_COUNT` INT NULL COMMENT '초기 닭의 수',
	`CURRENT_COUNT` INT NULL COMMENT '폐사체를 제외한 현재 닭의 수',
	`SHIPMENT_STATUS` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '출하 여부',
	`FARM_NUM` INT NOT NULL COMMENT '축사 아이디',
	PRIMARY KEY (`BATCH_ID`),
	FOREIGN KEY (`FARM_NUM`) REFERENCES `CHICKEN_FARM`(`FARM_NUM`)
);

CREATE TABLE `DANGER_NOTICE` (
	`NOTICE_NUM` INT AUTO_INCREMENT NOT NULL COMMENT '위험알림기록 번호',
	`NOTICE_CONTENT` VARCHAR(200) NOT NULL COMMENT '위험알림기록 내용',
	`NOTICE_CATEGORY` VARCHAR(20) NOT NULL COMMENT '위험알림 종류',
	`FARM_NUM` INT NOT NULL COMMENT '축사 아이디',
	`REC_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '위험 알림 기록 시간',
	PRIMARY KEY (`NOTICE_NUM`),
	FOREIGN KEY (`FARM_NUM`) REFERENCES `CHICKEN_FARM`(`FARM_NUM`)
);

CREATE TABLE `MEMBER` (
	`MEM_ID` VARCHAR(50) NOT NULL COMMENT '아이디',
	`MEM_PW` VARCHAR(255) NOT NULL COMMENT '비밀번호',
	`CONTACT` VARCHAR(20) NULL COMMENT '연락처',
	`NAME` VARCHAR(50) NOT NULL COMMENT '이름',
	`ROLE` ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER' COMMENT '권한',
	`FARM_ID` INT NOT NULL COMMENT '축사 아이디',
	`JOIN_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '멤버 등록 날짜',
	PRIMARY KEY (`MEM_ID`),
	FOREIGN KEY (`FARM_ID`) REFERENCES `CHICKEN_FARM`(`FARM_NUM`)
);

CREATE TABLE `NOTE` (
	`NOTE_NUM` INT AUTO_INCREMENT NOT NULL COMMENT '일지 아이디',
	`MEM_ID` VARCHAR(50) NOT NULL COMMENT '멤버 아이디',
	`REC_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '노트 기록 시간',
	PRIMARY KEY (`NOTE_NUM`),
	FOREIGN KEY (`MEM_ID`) REFERENCES `MEMBER`(`MEM_ID`)
);

CREATE TABLE `CHICKEN` (
	`CHICKEN_ID` INT AUTO_INCREMENT NOT NULL COMMENT '닭 개체 아이디',
	`RAW_WEIGHT` FLOAT NOT NULL DEFAULT 0 COMMENT '닭 몸무게',
	`AGE` INT NOT NULL DEFAULT 0 COMMENT '닭 나이',
	`GROWTH_STAGE` ENUM('CHICK','GROWER','FINISHER') NOT NULL DEFAULT 'CHICK' COMMENT '닭 성장 단계',
	`BATCH_ID` VARCHAR(20) NOT NULL COMMENT '배치 번호(EX>2025-001)',
	`FARM_NUM` INT NOT NULL COMMENT '축사 아이디',
	`HEALTH_STATUS` ENUM('HEALTHY', 'NORMAL', 'SICK') NOT NULL DEFAULT 'HEALTHY' COMMENT '닭 건강 상태',
	PRIMARY KEY (`CHICKEN_ID`),
	FOREIGN KEY (`BATCH_ID`) REFERENCES `CHICKEN_BATCH`(`BATCH_ID`),
	FOREIGN KEY (`FARM_NUM`) REFERENCES `CHICKEN_FARM`(`FARM_NUM`)
);

-- ERD 구조: CHICKEN_INOCULATION_HISTORY (개별 접종 이력)
CREATE TABLE `CHICKEN_INOCULATION_HISTORY` (
	`HISTORY_ID` INT AUTO_INCREMENT NOT NULL COMMENT '이력 번호',
	`CHICKEN_ID` INT NOT NULL COMMENT '닭 개체 아이디',
	`VACCINE_TYPE` ENUM('ND','HPAI','IBD','IB') NOT NULL COMMENT '백신 종류',
	`VACCINATION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '접종일',
	`VACCINATION_METHOD` VARCHAR(20) NULL COMMENT '접종 방법(음수/주사/분무 등)',
	`VACCINATED_BY` VARCHAR(30) NOT NULL COMMENT '접종 담당자',
	`NOTE` VARCHAR(200) NULL COMMENT '비고',
	PRIMARY KEY (`HISTORY_ID`, `CHICKEN_ID`),
	FOREIGN KEY (`CHICKEN_ID`) REFERENCES `CHICKEN`(`CHICKEN_ID`),
	INDEX `idx_chicken_vaccine` (`CHICKEN_ID`, `VACCINE_TYPE`)
);

-- ERD 구조: chicken_weight_history (REC_AGE 컬럼 포함)
CREATE TABLE `chicken_weight_history` (
	`HISTORY_ID` INT AUTO_INCREMENT NOT NULL COMMENT '이력 아이디',
	`CHICKEN_ID` INT NOT NULL COMMENT '닭 개체 아이디',
	`RAW_WEIGHT` FLOAT NOT NULL COMMENT '측정 무게',
	`REC_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '측정 시간',
	`REC_AGE` INT NOT NULL COMMENT '측정 당시 나이',
	PRIMARY KEY (`HISTORY_ID`),
	FOREIGN KEY (`CHICKEN_ID`) REFERENCES `CHICKEN`(`CHICKEN_ID`)
);

-- 조회 쿼리
SELECT * FROM danger_notice ORDER BY notice_num DESC;
SELECT * FROM farm_status ORDER BY farm_status_num DESC;
SELECT * FROM chicken_farm;
SELECT * FROM chicken_batch;
SELECT * FROM chicken_inoculation_history;
SELECT * FROM member;
SELECT * FROM chicken;
SELECT * FROM chicken_weight_history;
COMMIT;
