-- ENV_SETTINGS 테이블 업데이트 스크립트
-- 이 스크립트를 데이터베이스에서 실행하세요

-- 1. 새로운 컬럼들 추가
ALTER TABLE ENV_SETTINGS 
ADD COLUMN IF NOT EXISTS AUTO_LED_MODE BOOLEAN DEFAULT TRUE COMMENT 'LED 자동 모드 활성화',
ADD COLUMN IF NOT EXISTS MANUAL_LED_THRESHOLD DOUBLE DEFAULT 300 COMMENT '수동 LED 기준값 (lux)',
ADD COLUMN IF NOT EXISTS LOCATION_LAT DECIMAL(10, 8) DEFAULT 37.5665 COMMENT '위도 (서울 기본값)',
ADD COLUMN IF NOT EXISTS LOCATION_LNG DECIMAL(11, 8) DEFAULT 126.9780 COMMENT '경도 (서울 기본값)',
ADD COLUMN IF NOT EXISTS SLEEP_START_HOUR INT DEFAULT 22 COMMENT '수면 시작 시간 (24시간 형식)',
ADD COLUMN IF NOT EXISTS SLEEP_END_HOUR INT DEFAULT 6 COMMENT '수면 종료 시간 (24시간 형식)',
ADD COLUMN IF NOT EXISTS SLEEP_MODE_ENABLED BOOLEAN DEFAULT TRUE COMMENT '수면 모드 활성화';

-- 2. 기존 데이터가 있다면 새로운 컬럼에 기본값 설정
UPDATE ENV_SETTINGS SET 
    AUTO_LED_MODE = TRUE,
    MANUAL_LED_THRESHOLD = 300,
    LOCATION_LAT = 37.5665,
    LOCATION_LNG = 126.9780,
    SLEEP_START_HOUR = 22,
    SLEEP_END_HOUR = 6,
    SLEEP_MODE_ENABLED = TRUE
WHERE ID = 1;

-- 3. 테이블 구조 확인
DESCRIBE ENV_SETTINGS;

-- 4. 데이터 확인
SELECT * FROM ENV_SETTINGS WHERE ID = 1;
